// <auto-generated />
using Knight_Pratice.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Knight_Pratice.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210724185100_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knight_Pratice.Models.Data", b =>
                {
                    b.Property<int>("Data_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data_Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_Result")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Data_Id");

                    b.ToTable("Datas");
                });
#pragma warning restore 612, 618
        }
    }
}
